### ISSUE TITLE
CPP default client fails, invalid command being sent 

### ISSUE THREAD

**Issue by DevashishJoshi** [HUNTINGHOUND/cardnimarchitect#1]
Ran the server with command
`php server.php 5000 30 8`

Tried with both C++ clients and 1 Python and 1 C++, got the same error:

`PHP Notice:  Undefined index: 1getstate in /mnt/c/Users/Dev/HPS/cardnimarchitect-main/cardnimarchitect-main/server.php on line 180
[LOG] Invalid command: "sendmove 1getstate"`

(Command used to compile the cpp client: `g++ --std=c++20 client.cpp`)

Possible missing separator between 2 commands in the default C++ client code. Can you check if you can run with a C++ client or both C++ clients?

System used: Linux
PHP version: 7.4.28
g++ version: 10.3.0

The game works with other clients.

**Comment by DevashishJoshi** [comment]
Update: Changing the sleep value in the client with command:
`usleep(20000);`
fixed the issue. Added the same line before sending get_state command as well.

**Comment by phuang07** [comment]
Hi @DevashishJoshi, 
Thanks for reporting the issue and the possible fix. 

I double checked, and run the game with c++ (v13.0.0 on intel mac) client and python (v3.9) and the game is working fine. I am also on PHP v7.4.28 

I will have my teammate @HUNTINGHOUND to double check to see if he can reproduce the issue.
